// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIR8Cr70RQ6znbv1UDjke0x-jB8z1UY6s',
    appId: '1:711052641324:web:14f90502d238b954013d89',
    messagingSenderId: '711052641324',
    projectId: 'habitue-se-32fbe',
    authDomain: 'habitue-se-32fbe.firebaseapp.com',
    storageBucket: 'habitue-se-32fbe.firebasestorage.app',
    measurementId: 'G-E6HE2PLD84',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNX-NjJsm1awrIk6vyXXxZMpE1MN8xgm4',
    appId: '1:711052641324:android:e60dd6ea17764caa013d89',
    messagingSenderId: '711052641324',
    projectId: 'habitue-se-32fbe',
    storageBucket: 'habitue-se-32fbe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj_zbQR9k8BlWSrbEe1antO0zFvp_3MKE',
    appId: '1:711052641324:ios:ec7512e048d929ff013d89',
    messagingSenderId: '711052641324',
    projectId: 'habitue-se-32fbe',
    storageBucket: 'habitue-se-32fbe.firebasestorage.app',
    iosBundleId: 'com.example.habitueSe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIR8Cr70RQ6znbv1UDjke0x-jB8z1UY6s',
    appId: '1:711052641324:web:ba690fdbe9be16a1013d89',
    messagingSenderId: '711052641324',
    projectId: 'habitue-se-32fbe',
    authDomain: 'habitue-se-32fbe.firebaseapp.com',
    storageBucket: 'habitue-se-32fbe.firebasestorage.app',
    measurementId: 'G-4SG33V8BR9',
  );
}
